# Generated by Django 3.0 on 2022-07-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56)),
                ('contenr', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=120)),
                ('liked_by', models.CharField(max_length=120)),
            ],
        ),
    ]
