# Generated by Django 3.0 on 2022-07-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='contenr',
            new_name='content',
        ),
    ]
