# Generated by Django 3.0 on 2022-07-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_auto_20220722_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('price', models.PositiveIntegerField(default=5000)),
                ('band', models.CharField(default='4g', max_length=150)),
                ('display', models.CharField(max_length=120)),
                ('processor', models.CharField(max_length=120)),
            ],
        ),
    ]
