# Generated by Django 3.0 on 2022-08-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_auto_20220805_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='review',
            new_name='reviews',
        ),
    ]
